export interface Session {
  id: string;
  userId: string;
  timestamp: Date;
  durationSeconds: number;
  exercises: string[];
  painLevel: number; // 1-10
  accuracyScore: number; // Percentage
  averageAngle?: number;
  reps?: number;
  aiSummary: string; // Generated by Gemini
}

export interface UserProfile {
  uid: string;
  displayName: string | null;
  email: string | null;
  photoURL: string | null;
}

export enum ViewState {
  DASHBOARD = 'DASHBOARD',
  SESSION = 'SESSION',
  REPORT = 'REPORT',
}

// MediaPipe Global Types
declare global {
  interface Window {
    Pose: any;
    Camera: any;
    drawConnectors: any;
    drawLandmarks: any;
    POSE_CONNECTIONS: any;
  }
}